[build]
  command = "npm run build"
  publish = "dist"

# Fallback SPA (Vite)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache long des assets versionnés
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
